In [1]:
import numpy as np 
import pandas as pd 
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("new.xls")

In [3]:
df

,Timestamp,Username,Name,Gender,Personal Email,Roll No e.g TE_A_12,PRN No,Mobile No,First Year : Sem I CGPA,First Year : Sem II CGPA,Second Year : Sem I CGPA,Second Year : Sem II CGPA,First Year : Sem I CGPA,First Year : Sem II CGPA,Second Year : Sem I CGPA,Second Year : Sem II CGPA
0,2026/02/04 10:44:17 AM GMT+5:30,deshmukh.spandan@dypic.in,Spandan,Female,spandandeshmukh7@gmail.com,TE_A_42,72331972D,8767791226,8.45,8.95,9.18,9.18,NaN,NaN,NaN,NaN
1,2026/02/04 10:45:32 AM GMT+5:30,dipanshuambilker@gmail.com,Dipanshu Ambilkar,Male,dipanshuambilker@gmail.com,TE_A_49,72331987B,9893459282,9.68,9.24,9.45,9.36,NaN,NaN,NaN,NaN
2,2026/02/04 10:45:34 AM GMT+5:30,dhembare.durga@dypic.in,Durga Namdev Dhembare,Female,durgadhembare57@gmail.com,TE_A_46,72331981C,9730782780,7.1,6.7,7.60,8.7,NaN,NaN,NaN,NaN
3,2026/02/04 10:47:01 AM GMT+5:30,arpit.metkar@dypic.in,Arpit Metkar,Male,earthians7.9b@gmail.com,TE_A_13,72331872H,9403641970,9.05,8.05,6.91,8.05,NaN,NaN,NaN,NaN
4,2026/02/04 10:47:37 AM GMT+5:30,bhaktibhumare@gmail.com,Bhakti Anil Bhumare,Female,bhumarebhakti123@gmail.com,TE_A_27,72451658B,9834597784,8.7,NaN,8.66,8.77,NaN,NaN,NaN,NaN
5,2026/02/04 10:47:53 AM GMT+5:30,dhaygudeabhishek7@gmail.com,Abhishek kantilal dhaygude,Male,dhaygudeabhishek7@gmail.com,TE A 45,72451663J,8830043430,-,-,8.23,8.23,NaN,NaN,NaN,NaN
6,2026/02/04 10:48:02 AM GMT+5:30,chavhan.nilesh@dypic.in,Nilesh chavhan,Male,nileshchavhan631@gmail.com,TE_A_34,72331950C,9325546556,5.56,6.66,7.67,Statistics back,NaN,NaN,NaN,NaN
7,2026/02/04 05:47:35 AM GMT+5:30,student1@gmail.com,Komal Shinde,Female,komal1@gmail.com,TE_A_60,72510000A,9966263185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2026/02/04 05:48:35 AM GMT+5:30,student2@gmail.com,Shraddha Deshmukh,Female,shraddha2@gmail.com,TE_A_61,72510001A,7645194074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2026/02/04 05:49:35 AM GMT+5:30,student3@gmail.com,Vaishnavi Pawar,Female,vaishnavi3@gmail.com,TE_A_62,72510002A,7932746163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2026/02/04 05:50:35 AM GMT+5:30,student4@gmail.com,Aishwarya Shinde,Female,aishwarya4@gmail.com,TE_A_63,72510003A,8069290318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2026/02/04 05:51:35 AM GMT+5:30,student5@gmail.com,Rohit Deshmukh,Male,rohit5@gmail.com,TE_A_64,72510004A,8168531267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2026/02/04 05:52:35 AM GMT+5:30,student6@gmail.com,Om Deshmukh,Male,om6@gmail.com,TE_A_65,72510005A,7732875814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2026/02/04 05:53:35 AM GMT+5:30,student7@gmail.com,Komal Jadhav,Female,komal7@gmail.com,TE_A_66,72510006A,9020383820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2026/02/04 05:54:35 AM GMT+5:30,student8@gmail.com,Sneha Shinde,Female,sneha8@gmail.com,TE_A_67,72510007A,8117392456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2026/02/04 05:55:35 AM GMT+5:30,student9@gmail.com,Rahul Jadhav,Male,rahul9@gmail.com,TE_A_68,72510008A,7118139649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2026/02/04 05:56:35 AM GMT+5:30,student10@gmail.com,Shraddha Shinde,Female,shraddha10@gmail.com,TE_A_69,72510009A,9624237390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2026/02/04 05:57:35 AM GMT+5:30,student11@gmail.com,Komal Patil,Female,komal11@gmail.com,TE_A_70,72510010A,7878510190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2026/02/04 05:58:35 AM GMT+5:30,student12@gmail.com,Aditya Deshmukh,Male,aditya12@gmail.com,TE_A_71,72510011A,7003824741,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2026/02/04 05:59:35 AM GMT+5:30,student13@gmail.com,Neha Joshi,Female,neha13@gmail.com,TE_A_72,72510012A,8273616387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2026/02/04 06:00:35 AM GMT+5:30,student14@gmail.com,Aishwarya More,Female,aishwarya14@gmail.com,TE_A_73,72510013A,8976019277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2026/02/04 06:01:35 AM GMT+5:30,student15@gmail.com,Aishwarya Kulkarni,Female,aishwarya15@gmail.com,TE_A_74,72510014A,8256784763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2026/02/04 06:02:35 AM GMT+5:30,student16@gmail.com,Kunal Jadhav,Male,kunal16@gmail.com,TE_A_75,72510015A,9800073210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2026/02/04 06:03:35 AM GMT+5:30,student17@gmail.com,Om Kulkarni,Male,om17@gmail.com,TE_A_76,72510016A,7122997773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2026/02/04 06:04:35 AM GMT+5:30,student18@gmail.com,Yash Deshmukh,Male,yash18@gmail.com,TE_A_77,72510017A,9455443466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2026/02/04 06:05:35 AM GMT+5:30,student19@gmail.com,Sneha Jadhav,Female,sneha19@gmail.com,TE_A_78,72510018A,9072947254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2026/02/04 06:06:35 AM GMT+5:30,student20@gmail.com,Priya Jadhav,Female,priya20@gmail.com,TE_A_79,72510019A,9342929795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Timestamp                    27 non-null     object
 1   Username                     27 non-null     object
 2   Name                         27 non-null     object
 3   Gender                       27 non-null     object
 4   Personal Email               27 non-null     object
 5   Roll No e.g TE_A_12          27 non-null     object
 6   PRN No                       27 non-null     object
 7   Mobile No                    27 non-null     int64
 8   First Year :  Sem I CGPA     7 non-null      object
 9   First Year :  Sem II  CGPA   6 non-null      object
 10  Second Year :  Sem I  CGPA   7 non-null      float64
 11  Second Year :  Sem II  CGPA  7 non-null      object
 12  First Year : Sem I CGPA      0 non-null      float64
 13  First Year : Sem II CGPA     0 non-null      float64
 14  Second Year : Sem I CGPA     0 non-null      float64
 15  Second Year : Sem II CGPA    0 non-null      float64
dtypes: float64(5), int64(1), object(10)
memory usage: 3.5+ KB

In [5]:
df.isnull().sum()

Timestamp                       0
Username                        0
Name                            0
Gender                          0
Personal Email                  0
Roll No e.g TE_A_12             0
PRN No                          0
Mobile No                       0
First Year :  Sem I CGPA       20
First Year :  Sem II  CGPA     21
Second Year :  Sem I  CGPA     20
Second Year :  Sem II  CGPA    20
First Year : Sem I CGPA        27
First Year : Sem II CGPA       27
Second Year : Sem I CGPA       27
Second Year : Sem II CGPA      27
dtype: int64

In [6]:
df.head()

,Timestamp,Username,Name,Gender,Personal Email,Roll No e.g TE_A_12,PRN No,Mobile No,First Year : Sem I CGPA,First Year : Sem II CGPA,Second Year : Sem I CGPA,Second Year : Sem II CGPA,First Year : Sem I CGPA,First Year : Sem II CGPA,Second Year : Sem I CGPA,Second Year : Sem II CGPA
0,2026/02/04 10:44:17 AM GMT+5:30,deshmukh.spandan@dypic.in,Spandan,Female,spandandeshmukh7@gmail.com,TE_A_42,72331972D,8767791226,8.45,8.95,9.18,9.18,NaN,NaN,NaN,NaN
1,2026/02/04 10:45:32 AM GMT+5:30,dipanshuambilker@gmail.com,Dipanshu Ambilkar,Male,dipanshuambilker@gmail.com,TE_A_49,72331987B,9893459282,9.68,9.24,9.45,9.36,NaN,NaN,NaN,NaN
2,2026/02/04 10:45:34 AM GMT+5:30,dhembare.durga@dypic.in,Durga Namdev Dhembare,Female,durgadhembare57@gmail.com,TE_A_46,72331981C,9730782780,7.1,6.7,7.60,8.7,NaN,NaN,NaN,NaN
3,2026/02/04 10:47:01 AM GMT+5:30,arpit.metkar@dypic.in,Arpit Metkar,Male,earthians7.9b@gmail.com,TE_A_13,72331872H,9403641970,9.05,8.05,6.91,8.05,NaN,NaN,NaN,NaN
4,2026/02/04 10:47:37 AM GMT+5:30,bhaktibhumare@gmail.com,Bhakti Anil Bhumare,Female,bhumarebhakti123@gmail.com,TE_A_27,72451658B,9834597784,8.7,NaN,8.66,8.77,NaN,NaN,NaN,NaN

In [7]:
df.tail()

,Timestamp,Username,Name,Gender,Personal Email,Roll No e.g TE_A_12,PRN No,Mobile No,First Year : Sem I CGPA,First Year : Sem II CGPA,Second Year : Sem I CGPA,Second Year : Sem II CGPA,First Year : Sem I CGPA,First Year : Sem II CGPA,Second Year : Sem I CGPA,Second Year : Sem II CGPA
22,2026/02/04 06:02:35 AM GMT+5:30,student16@gmail.com,Kunal Jadhav,Male,kunal16@gmail.com,TE_A_75,72510015A,9800073210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2026/02/04 06:03:35 AM GMT+5:30,student17@gmail.com,Om Kulkarni,Male,om17@gmail.com,TE_A_76,72510016A,7122997773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2026/02/04 06:04:35 AM GMT+5:30,student18@gmail.com,Yash Deshmukh,Male,yash18@gmail.com,TE_A_77,72510017A,9455443466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2026/02/04 06:05:35 AM GMT+5:30,student19@gmail.com,Sneha Jadhav,Female,sneha19@gmail.com,TE_A_78,72510018A,9072947254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2026/02/04 06:06:35 AM GMT+5:30,student20@gmail.com,Priya Jadhav,Female,priya20@gmail.com,TE_A_79,72510019A,9342929795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.isnull().sum()

Timestamp                       0
Username                        0
Name                            0
Gender                          0
Personal Email                  0
Roll No e.g TE_A_12             0
PRN No                          0
Mobile No                       0
First Year :  Sem I CGPA       20
First Year :  Sem II  CGPA     21
Second Year :  Sem I  CGPA     20
Second Year :  Sem II  CGPA    20
First Year : Sem I CGPA        27
First Year : Sem II CGPA       27
Second Year : Sem I CGPA       27
Second Year : Sem II CGPA      27
dtype: int64

In [9]:
df = df.loc[:,~df.columns.duplicated()]

In [10]:
df

,Timestamp,Username,Name,Gender,Personal Email,Roll No e.g TE_A_12,PRN No,Mobile No,First Year : Sem I CGPA,First Year : Sem II CGPA,Second Year : Sem I CGPA,Second Year : Sem II CGPA,First Year : Sem I CGPA,First Year : Sem II CGPA,Second Year : Sem I CGPA,Second Year : Sem II CGPA
0,2026/02/04 10:44:17 AM GMT+5:30,deshmukh.spandan@dypic.in,Spandan,Female,spandandeshmukh7@gmail.com,TE_A_42,72331972D,8767791226,8.45,8.95,9.18,9.18,NaN,NaN,NaN,NaN
1,2026/02/04 10:45:32 AM GMT+5:30,dipanshuambilker@gmail.com,Dipanshu Ambilkar,Male,dipanshuambilker@gmail.com,TE_A_49,72331987B,9893459282,9.68,9.24,9.45,9.36,NaN,NaN,NaN,NaN
2,2026/02/04 10:45:34 AM GMT+5:30,dhembare.durga@dypic.in,Durga Namdev Dhembare,Female,durgadhembare57@gmail.com,TE_A_46,72331981C,9730782780,7.1,6.7,7.60,8.7,NaN,NaN,NaN,NaN
3,2026/02/04 10:47:01 AM GMT+5:30,arpit.metkar@dypic.in,Arpit Metkar,Male,earthians7.9b@gmail.com,TE_A_13,72331872H,9403641970,9.05,8.05,6.91,8.05,NaN,NaN,NaN,NaN
4,2026/02/04 10:47:37 AM GMT+5:30,bhaktibhumare@gmail.com,Bhakti Anil Bhumare,Female,bhumarebhakti123@gmail.com,TE_A_27,72451658B,9834597784,8.7,NaN,8.66,8.77,NaN,NaN,NaN,NaN
5,2026/02/04 10:47:53 AM GMT+5:30,dhaygudeabhishek7@gmail.com,Abhishek kantilal dhaygude,Male,dhaygudeabhishek7@gmail.com,TE A 45,72451663J,8830043430,-,-,8.23,8.23,NaN,NaN,NaN,NaN
6,2026/02/04 10:48:02 AM GMT+5:30,chavhan.nilesh@dypic.in,Nilesh chavhan,Male,nileshchavhan631@gmail.com,TE_A_34,72331950C,9325546556,5.56,6.66,7.67,Statistics back,NaN,NaN,NaN,NaN
7,2026/02/04 05:47:35 AM GMT+5:30,student1@gmail.com,Komal Shinde,Female,komal1@gmail.com,TE_A_60,72510000A,9966263185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2026/02/04 05:48:35 AM GMT+5:30,student2@gmail.com,Shraddha Deshmukh,Female,shraddha2@gmail.com,TE_A_61,72510001A,7645194074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2026/02/04 05:49:35 AM GMT+5:30,student3@gmail.com,Vaishnavi Pawar,Female,vaishnavi3@gmail.com,TE_A_62,72510002A,7932746163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2026/02/04 05:50:35 AM GMT+5:30,student4@gmail.com,Aishwarya Shinde,Female,aishwarya4@gmail.com,TE_A_63,72510003A,8069290318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2026/02/04 05:51:35 AM GMT+5:30,student5@gmail.com,Rohit Deshmukh,Male,rohit5@gmail.com,TE_A_64,72510004A,8168531267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2026/02/04 05:52:35 AM GMT+5:30,student6@gmail.com,Om Deshmukh,Male,om6@gmail.com,TE_A_65,72510005A,7732875814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2026/02/04 05:53:35 AM GMT+5:30,student7@gmail.com,Komal Jadhav,Female,komal7@gmail.com,TE_A_66,72510006A,9020383820,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2026/02/04 05:54:35 AM GMT+5:30,student8@gmail.com,Sneha Shinde,Female,sneha8@gmail.com,TE_A_67,72510007A,8117392456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2026/02/04 05:55:35 AM GMT+5:30,student9@gmail.com,Rahul Jadhav,Male,rahul9@gmail.com,TE_A_68,72510008A,7118139649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2026/02/04 05:56:35 AM GMT+5:30,student10@gmail.com,Shraddha Shinde,Female,shraddha10@gmail.com,TE_A_69,72510009A,9624237390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2026/02/04 05:57:35 AM GMT+5:30,student11@gmail.com,Komal Patil,Female,komal11@gmail.com,TE_A_70,72510010A,7878510190,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2026/02/04 05:58:35 AM GMT+5:30,student12@gmail.com,Aditya Deshmukh,Male,aditya12@gmail.com,TE_A_71,72510011A,7003824741,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2026/02/04 05:59:35 AM GMT+5:30,student13@gmail.com,Neha Joshi,Female,neha13@gmail.com,TE_A_72,72510012A,8273616387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2026/02/04 06:00:35 AM GMT+5:30,student14@gmail.com,Aishwarya More,Female,aishwarya14@gmail.com,TE_A_73,72510013A,8976019277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2026/02/04 06:01:35 AM GMT+5:30,student15@gmail.com,Aishwarya Kulkarni,Female,aishwarya15@gmail.com,TE_A_74,72510014A,8256784763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2026/02/04 06:02:35 AM GMT+5:30,student16@gmail.com,Kunal Jadhav,Male,kunal16@gmail.com,TE_A_75,72510015A,9800073210,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2026/02/04 06:03:35 AM GMT+5:30,student17@gmail.com,Om Kulkarni,Male,om17@gmail.com,TE_A_76,72510016A,7122997773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2026/02/04 06:04:35 AM GMT+5:30,student18@gmail.com,Yash Deshmukh,Male,yash18@gmail.com,TE_A_77,72510017A,9455443466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2026/02/04 06:05:35 AM GMT+5:30,student19@gmail.com,Sneha Jadhav,Female,sneha19@gmail.com,TE_A_78,72510018A,9072947254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2026/02/04 06:06:35 AM GMT+5:30,student20@gmail.com,Priya Jadhav,Female,priya20@gmail.com,TE_A_79,72510019A,9342929795,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.columns = df.columns.str.strip()

In [12]:
df.replace(['-', 'Statistics back', ' '], np.nan, inplace=True)

In [13]:

# CGPA columns
cgpa_cols = [
    'First Year :  Sem I CGPA',
    'First Year :  Sem II  CGPA',
    'Second Year :  Sem I  CGPA',
    'Second Year :  Sem II  CGPA'
]

for col in cgpa_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

df[cgpa_cols] = df[cgpa_cols].fillna(df[cgpa_cols].mean())

In [14]:
df[cgpa_cols]

,First Year : Sem I CGPA,First Year : Sem II CGPA,Second Year : Sem I CGPA,Second Year : Sem II CGPA
0,8.45,8.95,9.180000,9.180
1,9.68,9.24,9.450000,9.360
2,7.10,6.70,7.600000,8.700
3,9.05,8.05,6.910000,8.050
4,8.70,7.92,8.660000,8.770
5,8.09,7.92,8.230000,8.230
6,5.56,6.66,7.670000,8.715
7,8.09,7.92,8.242857,8.715
8,8.09,7.92,8.242857,8.715
9,8.09,7.92,8.242857,8.715
10,8.09,7.92,8.242857,8.715
11,8.09,7.92,8.242857,8.715
12,8.09,7.92,8.242857,8.715
13,8.09,7.92,8.242857,8.715
14,8.09,7.92,8.242857,8.715
15,8.09,7.92,8.242857,8.715
16,8.09,7.92,8.242857,8.715
17,8.09,7.92,8.242857,8.715
18,8.09,7.92,8.242857,8.715
19,8.09,7.92,8.242857,8.715
20,8.09,7.92,8.242857,8.715
21,8.09,7.92,8.242857,8.715
22,8.09,7.92,8.242857,8.715
23,8.09,7.92,8.242857,8.715
24,8.09,7.92,8.242857,8.715
25,8.09,7.92,8.242857,8.715
26,8.09,7.92,8.242857,8.715

In [16]:
import seaborn as sns 
import matplotlib.pyplot as plt
# sns.boxplot(data=df,x=cgpa_cols['First Year : Sem I CGPA'])
# plt.show()

In [25]:
df['Roll No e.g TE_A_12'] = df['Roll No e.g TE_A_12'].str.replace(' ', '_')

for col in cgpa_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    # cap outliers
    df[col] = np.where(df[col] < lower, lower, df[col])
    df[col] = np.where(df[col] > upper, upper, df[col])

In [26]:
lower

np.float64(8.715)

In [27]:
upper

np.float64(8.715)

In [ ]:
df.drop(columns=[''])

In [20]:
scaler = StandardScaler()
df_scaled = df.copy()
df_scaled[cgpa_cols] = scaler.fit_transform(df_scaled[cgpa_cols])

print("Cleaned Dataset:")
print(df.head())

print("\nScaled CGPA Dataset:")
print(df_scaled[cgpa_cols].head())

Cleaned Dataset:
                         Timestamp                    Username  \
0  2026/02/04 10:44:17 AM GMT+5:30   deshmukh.spandan@dypic.in
1  2026/02/04 10:45:32 AM GMT+5:30  dipanshuambilker@gmail.com
2  2026/02/04 10:45:34 AM GMT+5:30     dhembare.durga@dypic.in
3  2026/02/04 10:47:01 AM GMT+5:30       arpit.metkar@dypic.in
4  2026/02/04 10:47:37 AM GMT+5:30     bhaktibhumare@gmail.com

                     Name   Gender              Personal Email  \
0                Spandan   Female   spandandeshmukh7@gmail.com
1      Dipanshu Ambilkar     Male   dipanshuambilker@gmail.com
2  Durga Namdev Dhembare   Female    durgadhembare57@gmail.com
3            Arpit Metkar     Male     earthians7.9b@gmail.com
4    Bhakti Anil Bhumare   Female   bhumarebhakti123@gmail.com

  Roll No e.g TE_A_12     PRN No   Mobile No  First Year :  Sem I CGPA  \
0             TE_A_42  72331972D  8767791226                      8.09
1             TE_A_49  72331987B  9893459282                      8.09
2             TE_A_46  72331981C  9730782780                      8.09
3             TE_A_13  72331872H  9403641970                      8.09
4             TE_A_27  72451658B  9834597784                      8.09

   First Year :  Sem II  CGPA  Second Year :  Sem I  CGPA  \
0                        7.92                    8.242857
1                        7.92                    8.242857
2                        7.92                    8.242857
3                        7.92                    8.242857
4                        7.92                    8.242857

   Second Year :  Sem II  CGPA  First Year : Sem I CGPA  \
0                        8.715                      NaN
1                        8.715                      NaN
2                        8.715                      NaN
3                        8.715                      NaN
4                        8.715                      NaN

   First Year : Sem II CGPA  Second Year : Sem I CGPA  \
0                       NaN                       NaN
1                       NaN                       NaN
2                       NaN                       NaN
3                       NaN                       NaN
4                       NaN                       NaN

   Second Year : Sem II CGPA
0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN

Scaled CGPA Dataset:
   First Year :  Sem I CGPA  First Year :  Sem II  CGPA  \
0                       0.0                8.881784e-16
1                       0.0                8.881784e-16
2                       0.0                8.881784e-16
3                       0.0                8.881784e-16
4                       0.0                8.881784e-16

   Second Year :  Sem I  CGPA  Second Year :  Sem II  CGPA
0                1.776357e-15                          0.0
1                1.776357e-15                          0.0
2                1.776357e-15                          0.0
3                1.776357e-15                          0.0
4                1.776357e-15                          0.0

In [21]:
df['avg'] = df[cgpa_cols].mean()

In [22]:
df

,Timestamp,Username,Name,Gender,Personal Email,Roll No e.g TE_A_12,PRN No,Mobile No,First Year : Sem I CGPA,First Year : Sem II CGPA,Second Year : Sem I CGPA,Second Year : Sem II CGPA,First Year : Sem I CGPA,First Year : Sem II CGPA,Second Year : Sem I CGPA,Second Year : Sem II CGPA,avg
0,2026/02/04 10:44:17 AM GMT+5:30,deshmukh.spandan@dypic.in,Spandan,Female,spandandeshmukh7@gmail.com,TE_A_42,72331972D,8767791226,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
1,2026/02/04 10:45:32 AM GMT+5:30,dipanshuambilker@gmail.com,Dipanshu Ambilkar,Male,dipanshuambilker@gmail.com,TE_A_49,72331987B,9893459282,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
2,2026/02/04 10:45:34 AM GMT+5:30,dhembare.durga@dypic.in,Durga Namdev Dhembare,Female,durgadhembare57@gmail.com,TE_A_46,72331981C,9730782780,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
3,2026/02/04 10:47:01 AM GMT+5:30,arpit.metkar@dypic.in,Arpit Metkar,Male,earthians7.9b@gmail.com,TE_A_13,72331872H,9403641970,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
4,2026/02/04 10:47:37 AM GMT+5:30,bhaktibhumare@gmail.com,Bhakti Anil Bhumare,Female,bhumarebhakti123@gmail.com,TE_A_27,72451658B,9834597784,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
5,2026/02/04 10:47:53 AM GMT+5:30,dhaygudeabhishek7@gmail.com,Abhishek kantilal dhaygude,Male,dhaygudeabhishek7@gmail.com,TE_A_45,72451663J,8830043430,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
6,2026/02/04 10:48:02 AM GMT+5:30,chavhan.nilesh@dypic.in,Nilesh chavhan,Male,nileshchavhan631@gmail.com,TE_A_34,72331950C,9325546556,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
7,2026/02/04 05:47:35 AM GMT+5:30,student1@gmail.com,Komal Shinde,Female,komal1@gmail.com,TE_A_60,72510000A,9966263185,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
8,2026/02/04 05:48:35 AM GMT+5:30,student2@gmail.com,Shraddha Deshmukh,Female,shraddha2@gmail.com,TE_A_61,72510001A,7645194074,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
9,2026/02/04 05:49:35 AM GMT+5:30,student3@gmail.com,Vaishnavi Pawar,Female,vaishnavi3@gmail.com,TE_A_62,72510002A,7932746163,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
10,2026/02/04 05:50:35 AM GMT+5:30,student4@gmail.com,Aishwarya Shinde,Female,aishwarya4@gmail.com,TE_A_63,72510003A,8069290318,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
11,2026/02/04 05:51:35 AM GMT+5:30,student5@gmail.com,Rohit Deshmukh,Male,rohit5@gmail.com,TE_A_64,72510004A,8168531267,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
12,2026/02/04 05:52:35 AM GMT+5:30,student6@gmail.com,Om Deshmukh,Male,om6@gmail.com,TE_A_65,72510005A,7732875814,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
13,2026/02/04 05:53:35 AM GMT+5:30,student7@gmail.com,Komal Jadhav,Female,komal7@gmail.com,TE_A_66,72510006A,9020383820,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
14,2026/02/04 05:54:35 AM GMT+5:30,student8@gmail.com,Sneha Shinde,Female,sneha8@gmail.com,TE_A_67,72510007A,8117392456,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
15,2026/02/04 05:55:35 AM GMT+5:30,student9@gmail.com,Rahul Jadhav,Male,rahul9@gmail.com,TE_A_68,72510008A,7118139649,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
16,2026/02/04 05:56:35 AM GMT+5:30,student10@gmail.com,Shraddha Shinde,Female,shraddha10@gmail.com,TE_A_69,72510009A,9624237390,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
17,2026/02/04 05:57:35 AM GMT+5:30,student11@gmail.com,Komal Patil,Female,komal11@gmail.com,TE_A_70,72510010A,7878510190,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
18,2026/02/04 05:58:35 AM GMT+5:30,student12@gmail.com,Aditya Deshmukh,Male,aditya12@gmail.com,TE_A_71,72510011A,7003824741,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
19,2026/02/04 05:59:35 AM GMT+5:30,student13@gmail.com,Neha Joshi,Female,neha13@gmail.com,TE_A_72,72510012A,8273616387,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
20,2026/02/04 06:00:35 AM GMT+5:30,student14@gmail.com,Aishwarya More,Female,aishwarya14@gmail.com,TE_A_73,72510013A,8976019277,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
21,2026/02/04 06:01:35 AM GMT+5:30,student15@gmail.com,Aishwarya Kulkarni,Female,aishwarya15@gmail.com,TE_A_74,72510014A,8256784763,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
22,2026/02/04 06:02:35 AM GMT+5:30,student16@gmail.com,Kunal Jadhav,Male,kunal16@gmail.com,TE_A_75,72510015A,9800073210,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
23,2026/02/04 06:03:35 AM GMT+5:30,student17@gmail.com,Om Kulkarni,Male,om17@gmail.com,TE_A_76,72510016A,7122997773,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
24,2026/02/04 06:04:35 AM GMT+5:30,student18@gmail.com,Yash Deshmukh,Male,yash18@gmail.com,TE_A_77,72510017A,9455443466,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
25,2026/02/04 06:05:35 AM GMT+5:30,student19@gmail.com,Sneha Jadhav,Female,sneha19@gmail.com,TE_A_78,72510018A,9072947254,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN
26,2026/02/04 06:06:35 AM GMT+5:30,student20@gmail.com,Priya Jadhav,Female,priya20@gmail.com,TE_A_79,72510019A,9342929795,8.09,7.92,8.242857,8.715,NaN,NaN,NaN,NaN,NaN

Empty DataFrame
Columns: [Timestamp, Username, Name, Gender, Personal Email, Roll No e.g TE_A_12, PRN No, Mobile No, First Year :  Sem I CGPA, First Year :  Sem II  CGPA, Second Year :  Sem I  CGPA, Second Year :  Sem II  CGPA, First Year : Sem I CGPA, First Year : Sem II CGPA, Second Year : Sem I CGPA, Second Year : Sem II CGPA, avg]
Index: []