In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("autodata - autodata.csv")

In [3]:
df.head()

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,13495,11.190476,Low,0,1
1,1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,...,9.0,111.0,5000.0,21,27,16500,11.190476,Low,0,1
2,2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,...,9.0,154.0,5000.0,19,26,16500,12.368421,Medium,0,1
3,3,2,164,audi,std,four,sedan,fwd,front,99.8,...,10.0,102.0,5500.0,24,30,13950,9.791667,Low,0,1
4,4,2,164,audi,std,four,sedan,4wd,front,99.4,...,8.0,115.0,5500.0,18,22,17450,13.055556,Low,0,1

In [4]:
df.tail()

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
196,196,-1,95,volvo,std,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,23,28,16845,10.217391,Low,0,1
197,197,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,8.7,160.0,5300.0,19,25,19045,12.368421,Medium,0,1
198,198,-1,95,volvo,std,four,sedan,rwd,front,109.1,...,8.8,134.0,5500.0,18,23,21485,13.055556,Medium,0,1
199,199,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,23.0,106.0,4800.0,26,27,22470,9.038462,Low,1,0
200,200,-1,95,volvo,turbo,four,sedan,rwd,front,109.1,...,9.5,114.0,5400.0,19,25,22625,12.368421,Low,0,1

In [5]:
df.shape

(201, 30)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         201 non-null    int64
 1   symboling          201 non-null    int64
 2   normalized-losses  201 non-null    int64
 3   make               201 non-null    object
 4   aspiration         201 non-null    object
 5   num-of-doors       201 non-null    object
 6   body-style         201 non-null    object
 7   drive-wheels       201 non-null    object
 8   engine-location    201 non-null    object
 9   wheel-base         201 non-null    float64
 10  length             201 non-null    float64
 11  width              201 non-null    float64
 12  height             201 non-null    float64
 13  curb-weight        201 non-null    int64
 14  engine-type        201 non-null    object
 15  num-of-cylinders   201 non-null    object
 16  engine-size        201 non-null    int64
 17  fuel-system        201 non-null    object
 18  bore               201 non-null    float64
 19  stroke             197 non-null    float64
 20  compression-ratio  201 non-null    float64
 21  horsepower         199 non-null    float64
 22  peak-rpm           199 non-null    float64
 23  city-mpg           201 non-null    int64
 24  highway-mpg        201 non-null    int64
 25  price              201 non-null    int64
 26  city-L/100km       201 non-null    float64
 27  horsepower-binned  199 non-null    object
 28  diesel             201 non-null    int64
 29  gas                201 non-null    int64
dtypes: float64(10), int64(10), object(10)
memory usage: 47.2+ KB

In [7]:
df.describe()

,Unnamed: 0,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
count,201.000000,201.000000,201.00000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000,197.000000,201.000000,199.000000,199.000000,201.000000,201.000000,201.000000,201.000000,201.000000,201.000000
mean,100.000000,0.840796,122.00000,98.797015,0.837102,0.915126,53.766667,2555.666667,126.875622,3.330692,3.256904,10.164279,103.396985,5117.587940,25.179104,30.686567,13207.129353,9.944145,0.099502,0.900498
std,58.167861,1.254802,31.99625,6.066366,0.059213,0.029187,2.447822,517.296727,41.546834,0.268072,0.319256,4.004965,37.553843,480.521824,6.423220,6.815150,7947.066342,2.534599,0.300083,0.300083
min,0.000000,-2.000000,65.00000,86.600000,0.678039,0.837500,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000,4.795918,0.000000,0.000000
25%,50.000000,0.000000,101.00000,94.500000,0.801538,0.890278,52.000000,2169.000000,98.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7775.000000,7.833333,0.000000,1.000000
50%,100.000000,1.000000,122.00000,97.000000,0.832292,0.909722,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000,9.791667,0.000000,1.000000
75%,150.000000,2.000000,137.00000,102.400000,0.881788,0.925000,55.500000,2926.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16500.000000,12.368421,0.000000,1.000000
max,200.000000,3.000000,256.00000,120.900000,1.000000,1.000000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,262.000000,6600.000000,49.000000,54.000000,45400.000000,18.076923,1.000000,1.000000

In [8]:
df.isnull().sum()

Unnamed: 0           0
symboling            0
normalized-losses    0
make                 0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                0
city-L/100km         0
horsepower-binned    2
diesel               0
gas                  0
dtype: int64

#### Empty/null values
- stroke - 4
- horsepower - 2 
- peak-rpm - 2
- horsepower-binned - 2

In [9]:
df[df['stroke'].isnull()]

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
52,52,3,150,mazda,std,two,hatchback,rwd,front,95.3,...,9.4,101.0,6000.0,17,23,10945,13.823529,Low,0,1
53,53,3,150,mazda,std,two,hatchback,rwd,front,95.3,...,9.4,101.0,6000.0,17,23,11845,13.823529,Low,0,1
54,54,3,150,mazda,std,two,hatchback,rwd,front,95.3,...,9.4,101.0,6000.0,17,23,13645,13.823529,Low,0,1
55,55,3,150,mazda,std,two,hatchback,rwd,front,95.3,...,9.4,135.0,6000.0,16,23,15645,14.687500,Medium,0,1

In [10]:
df[df['horsepower'].isnull()]

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
126,126,0,122,renault,std,four,wagon,fwd,front,96.1,...,8.7,NaN,NaN,23,31,9295,10.217391,NaN,0,1
127,127,2,122,renault,std,two,hatchback,fwd,front,96.1,...,8.7,NaN,NaN,23,31,9895,10.217391,NaN,0,1

In [11]:
df[df['peak-rpm'].isnull()]

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
126,126,0,122,renault,std,four,wagon,fwd,front,96.1,...,8.7,NaN,NaN,23,31,9295,10.217391,NaN,0,1
127,127,2,122,renault,std,two,hatchback,fwd,front,96.1,...,8.7,NaN,NaN,23,31,9895,10.217391,NaN,0,1

In [12]:
df[df['horsepower-binned'].isnull()]

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
126,126,0,122,renault,std,four,wagon,fwd,front,96.1,...,8.7,NaN,NaN,23,31,9295,10.217391,NaN,0,1
127,127,2,122,renault,std,two,hatchback,fwd,front,96.1,...,8.7,NaN,NaN,23,31,9895,10.217391,NaN,0,1

In [13]:
df['stroke'] = df['stroke'].fillna(method='ffill')
df['horsepower'] = df['horsepower'].fillna(method='ffill') 
df['peak-rpm'] = df['peak-rpm'].fillna(method='ffill') 
df['horsepower-binned'] = df['horsepower-binned'].fillna(method='ffill')

C:\Users\dipan\AppData\Local\Temp\ipykernel_6176\1434883142.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['stroke'] = df['stroke'].fillna(method='ffill')
C:\Users\dipan\AppData\Local\Temp\ipykernel_6176\1434883142.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['horsepower'] = df['horsepower'].fillna(method='ffill')
C:\Users\dipan\AppData\Local\Temp\ipykernel_6176\1434883142.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['peak-rpm'] = df['peak-rpm'].fillna(method='ffill')
C:\Users\dipan\AppData\Local\Temp\ipykernel_6176\1434883142.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['horsepower-binned'] = df['horsepower-binned'].fillna(method='ffill')

In [14]:
df.isnull().sum()

Unnamed: 0           0
symboling            0
normalized-losses    0
make                 0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
city-L/100km         0
horsepower-binned    0
diesel               0
gas                  0
dtype: int64

In [15]:
df.dtypes

Unnamed: 0             int64
symboling              int64
normalized-losses      int64
make                  object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                  int64
city-L/100km         float64
horsepower-binned     object
diesel                 int64
gas                    int64
dtype: object

In [16]:
df.sample()

,Unnamed: 0,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
40,40,0,85,honda,std,four,sedan,fwd,front,96.5,...,9.0,101.0,5800.0,24,28,12945,9.791667,Low,0,1

In [17]:
df.drop(columns=['Unnamed: 0'],inplace=True)

In [18]:
df.head(3)

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,13495,11.190476,Low,0,1
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,16500,11.190476,Low,0,1
2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,0.822681,...,9.0,154.0,5000.0,19,26,16500,12.368421,Medium,0,1

In [19]:
df['horsepower-binned'].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [20]:
df['aspiration'] = df['aspiration'].map({"std" : 0,"turbo": 1})

In [21]:
df['num-of-doors'] = df['num-of-doors'].map({"two" : 2,"four": 4})

In [22]:
df['num-of-cylinders'] = df['num-of-cylinders'].map({'four':4, 'six':6, 'five':5, 'three':3, 'twelve':11, 'two' :2, 'eight' : 8})

In [23]:
df['drive-wheels'] = df['drive-wheels'].map({"rwd" :0, "fwd": 1,"4wd" : 2})

In [24]:
df['engine-location'] = df['engine-location'].map({"front" : 0,"rear": 1})

In [25]:
df['horsepower-binned'] = df['horsepower-binned'].map({"Low" : 0,"Medium": 1,'High':2})

In [26]:
df

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,0,2,convertible,0,0,88.6,0.811148,...,9.0,111.0,5000.0,21,27,13495,11.190476,0,0,1
1,3,122,alfa-romero,0,2,convertible,0,0,88.6,0.811148,...,9.0,111.0,5000.0,21,27,16500,11.190476,0,0,1
2,1,122,alfa-romero,0,2,hatchback,0,0,94.5,0.822681,...,9.0,154.0,5000.0,19,26,16500,12.368421,1,0,1
3,2,164,audi,0,4,sedan,1,0,99.8,0.848630,...,10.0,102.0,5500.0,24,30,13950,9.791667,0,0,1
4,2,164,audi,0,4,sedan,2,0,99.4,0.848630,...,8.0,115.0,5500.0,18,22,17450,13.055556,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,0,4,sedan,0,0,109.1,0.907256,...,9.5,114.0,5400.0,23,28,16845,10.217391,0,0,1
197,-1,95,volvo,1,4,sedan,0,0,109.1,0.907256,...,8.7,160.0,5300.0,19,25,19045,12.368421,1,0,1
198,-1,95,volvo,0,4,sedan,0,0,109.1,0.907256,...,8.8,134.0,5500.0,18,23,21485,13.055556,1,0,1
199,-1,95,volvo,1,4,sedan,0,0,109.1,0.907256,...,23.0,106.0,4800.0,26,27,22470,9.038462,0,1,0
200,-1,95,volvo,1,4,sedan,0,0,109.1,0.907256,...,9.5,114.0,5400.0,19,25,22625,12.368421,0,0,1

In [27]:
df.dtypes

symboling              int64
normalized-losses      int64
make                  object
aspiration             int64
num-of-doors           int64
body-style            object
drive-wheels           int64
engine-location        int64
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders       int64
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                  int64
city-L/100km         float64
horsepower-binned      int64
diesel                 int64
gas                    int64
dtype: object

In [28]:
df

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,0,2,convertible,0,0,88.6,0.811148,...,9.0,111.0,5000.0,21,27,13495,11.190476,0,0,1
1,3,122,alfa-romero,0,2,convertible,0,0,88.6,0.811148,...,9.0,111.0,5000.0,21,27,16500,11.190476,0,0,1
2,1,122,alfa-romero,0,2,hatchback,0,0,94.5,0.822681,...,9.0,154.0,5000.0,19,26,16500,12.368421,1,0,1
3,2,164,audi,0,4,sedan,1,0,99.8,0.848630,...,10.0,102.0,5500.0,24,30,13950,9.791667,0,0,1
4,2,164,audi,0,4,sedan,2,0,99.4,0.848630,...,8.0,115.0,5500.0,18,22,17450,13.055556,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
196,-1,95,volvo,0,4,sedan,0,0,109.1,0.907256,...,9.5,114.0,5400.0,23,28,16845,10.217391,0,0,1
197,-1,95,volvo,1,4,sedan,0,0,109.1,0.907256,...,8.7,160.0,5300.0,19,25,19045,12.368421,1,0,1
198,-1,95,volvo,0,4,sedan,0,0,109.1,0.907256,...,8.8,134.0,5500.0,18,23,21485,13.055556,1,0,1
199,-1,95,volvo,1,4,sedan,0,0,109.1,0.907256,...,23.0,106.0,4800.0,26,27,22470,9.038462,0,1,0
200,-1,95,volvo,1,4,sedan,0,0,109.1,0.907256,...,9.5,114.0,5400.0,19,25,22625,12.368421,0,0,1